export const gameData = [
  {
    id: 1,
    icon: "fa-solid fa-house",
    name: "house",
    isSelected: false,
    isMatched: false,

   
  },
  {
    id: 2,
    icon:"fa-solid fa-star",
    name: "star",
    isSelected: false,
    isMatched: false,
    
  },
  {
    id: 3,
    icon: "fa-solid fa-heart",
    name: "heart",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 4,
    icon:"fa-solid fa-music",
    name: "music",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 5,
    icon: "fa-solid fa-bomb",
    name: "bomb",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 6,
    icon: "fa-solid fa-cloud",
    name: "cloud",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 7,
    icon: "fa-solid fa-bell",
    name: "bell",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 8,
    icon: "fa-solid fa-gift",
    name: "gift",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 9,
    icon: "fa-solid fa-house",
    name: "house",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 10,
    icon: "fa-solid fa-star",
    name: "star",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 11,
    icon: "fa-solid fa-heart",
    name: "heart",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 12,
    icon: "fa-solid fa-music",
    name: "music",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 13,
    icon: "fa-solid fa-bomb",
    name: "bomb",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 14,
    icon: "fa-solid fa-cloud",
    name: "cloud",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 15,
    icon: "fa-solid fa-bell",
    name: "bell",
    isSelected: false,
    isMatched: false,
  },
  {
    id: 16,
    icon: "fa-solid fa-gift",
    name: "gift",
    isSelected: false,
    isMatched: false,
  },
];
